### ISSUE TITLE
RuntimeError: "roll_cuda" not implemented for 'ComplexHalf'

### ISSUE THREAD

**Issue by Jayamoon59** [YuxinWenRick/tree-ring-watermark#10]
Hi, Sorry to bother you.
I am very interested in your project, but have some problems when I reproduce, 
such as "RuntimeError: "roll_cuda" not implemented for 'ComplexHalf'" , 
I didn't find any useful way to solve it, can you help me?

Looking forward to your reply！

**Comment by YuxinWenRick** [comment]
Hi, thanks for your interest!

To help me understand the issue better, could you please provide more context? Specifically, could you share the exact line of code causing the problem or the version of torch or diffusers you are using?

Thank you!

**Comment by YuxinWenRick** [comment]
Hello, it seems the issue might be related to the `torch.fft` module. I'm currently using PyTorch version 1.13.0. While I'm not certain of the exact differences in the `fft` implementation between versions, updating your PyTorch to version 1.13.0 may resolve the problem. Could you please try upgrading and let me know if it helps?

**Comment by Jayamoon59** [comment]
Thank you very much, PyTorch version 1.13.0 solves the problem perfectly.

 In addition, I would like to ask you a more technical question. In the future work of the article, you mentioned that "the accuracy of reverse diffusion can be improved". I would like to try if there is any clear instruction on which .py file to modify.

**Comment by YuxinWenRick** [comment]
Hi, I'm glad to hear that the issue has been resolved.

Yeah, right now, our implementation is using DDIM, and the inversion is not perfect as we mentioned in the paper. Therefore, we expect the inverted latent could be more accurate with better (deterministic) sampling methods. You can modify the scheduler when generating the image [here](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L27), and for inversion, you may want to modify this [part](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/inverse_stable_diffusion.py#L54C47-L54C65).

**Comment by YuxinWenRick** [comment]
Hi @Jayamoon59 , I just found this new [paper](https://arxiv.org/abs/2311.18387) that came up with a more accurate inversion process. In section 5.2., they applied their new inversion process to tree-ring and got a better result. Hope this is interesting to you.

Meanwhile, I'm gonna close this issue. Let me know if you have further questions!
