### ISSUE TITLE
debug error

### ISSUE THREAD

**Issue by jinganglang567** [YuxinWenRick/tree-ring-watermark#13]
hi i'm sorry to bother you,when i reduce the code ,i got the problem can you tell me what i need to do?

Traceback (most recent call last):
  File "D:\treering\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\treering\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\treering\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\treering\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "D:\treering\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "D:\treering\lib\site-packages\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "D:\treering\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "D:\treering\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001FEBAB75CD0>, 'Connection to huggingface
.co timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\treering\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\treering\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "D:\treering\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/st
able-diffusion-2-1-base/resolve/main/scheduler/scheduler_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnectio
n object at 0x000001FEBAB75CD0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\treering\lib\site-packages\huggingface_hub\file_download.py", line 1247, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "D:\treering\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\treering\lib\site-packages\huggingface_hub\file_download.py", line 1624, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\treering\lib\site-packages\huggingface_hub\file_download.py", line 402, in _request_wrapper
    response = _request_wrapper(
  File "D:\treering\lib\site-packages\huggingface_hub\file_download.py", line 425, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "D:\treering\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\treering\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\treering\lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "D:\treering\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with ur
l: /stabilityai/stable-diffusion-2-1-base/resolve/main/scheduler/scheduler_config.json (Caused by ConnectTimeoutError(<urllib3.connect
ion.HTTPSConnection object at 0x000001FEBAB75CD0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 4
3779387-774b-4ccb-9524-86ab46d4ce5d)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\treering\lib\site-packages\diffusers\configuration_utils.py", line 326, in load_config
    config_file = hf_hub_download(
  File "D:\treering\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\treering\lib\site-packages\huggingface_hub\file_download.py", line 1377, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find
 the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tree_ring_watermark.py", line 218, in <module>
    main(args)
  File "run_tree_ring_watermark.py", line 28, in main
    scheduler = DPMSolverMultistepScheduler.from_pretrained(args.model_id, subfolder='scheduler')
  File "D:\treering\lib\site-packages\diffusers\schedulers\scheduling_utils.py", line 118, in from_pretrained
    config, kwargs = cls.load_config(
  File "D:\treering\lib\site-packages\diffusers\configuration_utils.py", line 354, in load_config
    raise EnvironmentError(
OSError: stabilityai/stable-diffusion-2-1-base does not appear to have a file named scheduler_config.json.
wandb: You can sync this run to the cloud by running:
wandb: wandb sync C:\Users\LENOVO\Desktop\code\tree-ring-watermark\wandb\offline-run-20231213_205324-orwb3fbr
wandb: Find logs at: .\wandb\offline-run-20231213_205324-orwb3fbr\logs

**Comment by YuxinWenRick** [comment]
Hi, it seems there's an issue with Hugging Face when loading the model.

Could you double-check your diffusers version? I used version 0.11.1. Meanwhile, could you try a different model, such as changing the model_id to stabilityai/stable-diffusion-2-1?

**Comment by jinganglang567** [comment]
thanks, it worked

**Comment by jinganglang567** [comment]
sorry it doesn't worked

**Comment by Ssunyh** [comment]
> hi i'm sorry to bother you,when i reduce the code ,i got the problem can you tell me what i need to do?
> 
> Traceback (most recent call last): File "D:\treering\lib\site-packages\urllib3\connection.py", line 174, in _new_conn conn = connection.create_connection( File "D:\treering\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection raise err File "D:\treering\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection sock.connect(sa) socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\treering\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen httplib_response = self._make_request( File "D:\treering\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request self._validate_conn(conn) File "D:\treering\lib\site-packages\urllib3\connectionpool.py", line 1058, in _validate_conn conn.connect() File "D:\treering\lib\site-packages\urllib3\connection.py", line 363, in connect self.sock = conn = self._new_conn() File "D:\treering\lib\site-packages\urllib3\connection.py", line 179, in _new_conn raise ConnectTimeoutError( urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001FEBAB75CD0>, 'Connection to huggingface .co timed out. (connect timeout=10)')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\treering\lib\site-packages\requests\adapters.py", line 486, in send resp = conn.urlopen( File "D:\treering\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen retries = retries.increment( File "D:\treering\lib\site-packages\urllib3\util\retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/st able-diffusion-2-1-base/resolve/main/scheduler/scheduler_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnectio n object at 0x000001FEBAB75CD0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\treering\lib\site-packages\huggingface_hub\file_download.py", line 1247, in hf_hub_download metadata = get_hf_file_metadata( File "D:\treering\lib\site-packages\huggingface_hub\utils_validators.py", line 118, in _inner_fn return fn(*args, **kwargs) File "D:\treering\lib\site-packages\huggingface_hub\file_download.py", line 1624, in get_hf_file_metadata r = _request_wrapper( File "D:\treering\lib\site-packages\huggingface_hub\file_download.py", line 402, in _request_wrapper response = _request_wrapper( File "D:\treering\lib\site-packages\huggingface_hub\file_download.py", line 425, in _request_wrapper response = get_session().request(method=method, url=url, **params) File "D:\treering\lib\site-packages\requests\sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "D:\treering\lib\site-packages\requests\sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "D:\treering\lib\site-packages\huggingface_hub\utils_http.py", line 63, in send return super().send(request, *args, **kwargs) File "D:\treering\lib\site-packages\requests\adapters.py", line 507, in send raise ConnectTimeout(e, request=request) requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with ur l: /stabilityai/stable-diffusion-2-1-base/resolve/main/scheduler/scheduler_config.json (Caused by ConnectTimeoutError(<urllib3.connect ion.HTTPSConnection object at 0x000001FEBAB75CD0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 4 3779387-774b-4ccb-9524-86ab46d4ce5d)')
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "D:\treering\lib\site-packages\diffusers\configuration_utils.py", line 326, in load_config config_file = hf_hub_download( File "D:\treering\lib\site-packages\huggingface_hub\utils_validators.py", line 118, in _inner_fn return fn(*args, **kwargs) File "D:\treering\lib\site-packages\huggingface_hub\file_download.py", line 1377, in hf_hub_download raise LocalEntryNotFoundError( huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "run_tree_ring_watermark.py", line 218, in main(args) File "run_tree_ring_watermark.py", line 28, in main scheduler = DPMSolverMultistepScheduler.from_pretrained(args.model_id, subfolder='scheduler') File "D:\treering\lib\site-packages\diffusers\schedulers\scheduling_utils.py", line 118, in from_pretrained config, kwargs = cls.load_config( File "D:\treering\lib\site-packages\diffusers\configuration_utils.py", line 354, in load_config raise EnvironmentError( OSError: stabilityai/stable-diffusion-2-1-base does not appear to have a file named scheduler_config.json. wandb: You can sync this run to the cloud by running: wandb: wandb sync C:\Users\LENOVO\Desktop\code\tree-ring-watermark\wandb\offline-run-20231213_205324-orwb3fbr wandb: Find logs at: .\wandb\offline-run-20231213_205324-orwb3fbr\logs

I have the same problem. Could you tell me the solution?

**Comment by GHOSTANDBREAD** [comment]
hi, Have you solved your problem? I have also encountered this problem. If you have solved it, can you tell me your solution
