### ISSUE TITLE
how can i see the watermark that i implant?

### ISSUE THREAD

**Issue by jinganglang567** [YuxinWenRick/tree-ring-watermark#19]
if i want to know the image an watermark what i need to do

**Comment by YuxinWenRick** [comment]
Hi, if I understood it correctly, do you mean you want to visualize the watermark?

For example, if you want to visualize `init_latents_w_fft`, you can use this code snippet after [line 88](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L88):
```
        import matplotlib.pyplot as plt
        def visualize_tensor(tensor, name='./tmp.png'):
            channels = tensor.squeeze(0).cpu().numpy()
            fig, axs = plt.subplots(1, 4, figsize=(12, 3))

            for i, ax in enumerate(axs):
                ax.imshow(channels[i], cmap='gray')
                ax.set_title(f'Channel {i+1}')
                ax.axis('off')

            plt.savefig(name)
            plt.show()

        init_latents_w_fft = torch.fft.fftshift(torch.fft.fft2(init_latents_w), dim=(-1, -2)).real
        visualize_tensor(init_latents_w_fft, name='./real.png')
        init_latents_w_fft = torch.fft.fftshift(torch.fft.fft2(init_latents_w), dim=(-1, -2)).imag
        visualize_tensor(init_latents_w_fft, name='./imag.png')
```

Let me know if you have any problem with running it!

**Comment by jinganglang567** [comment]
doctor,sorry to bother you again, if i want to visualize the soure image and the image inject ,what should i do?

**Comment by YuxinWenRick** [comment]
Hi, do you mean you want to visualize the original generated image and the watermarked image? You can save `orig_image_no_w` and `orig_image_w` accordingly. Meanwhile, if you are using wandb, the generated images are logged to the report automatically [here](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L147).

**Comment by jinganglang567** [comment]
thanks

**Comment by YuxinWenRick** [comment]
Hi, I assume you set `reference_model` as null? Can you try to modify [this line](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L145) to `if i < args.max_num_log_image:`? This will log first `max_num_log_image` images, which is 100 by default.

**Comment by jinganglang567** [comment]
thank you,doctor, i will try

**Comment by jinganglang567** [comment]
@YuxinWenRick sorry to bother you again doctor,when i change the code. it show this in the wanb
![image](https://github.com/YuxinWenRick/tree-ring-watermark/assets/71933496/df8fd241-0cfb-41b3-8bf9-b14b5d620679)
![image](https://github.com/YuxinWenRick/tree-ring-watermark/assets/71933496/54decac5-af11-4aec-b5dd-d70f2043a1e2)
it didn't solve the problem,i run the "python run_tree_ring_watermark.py --run_name no_attack --w_channel 3 --w_pattern ring --start 0 --end 1000 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k"

**Comment by YuxinWenRick** [comment]
Hi @jinganglang567 , Im not sure what's going wrong here with wandb, but you may want to save them locally.

Can you try to add the following snippet of code to [here](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L150)? 

```
import os
from PIL import Image

if not os.path.exists("non_watermarked_images"):
    os.makedirs("non_watermarked_images")

if not os.path.exists("watermarked_images"):
    os.makedirs("watermarked_images")

orig_image_no_w.save(f"non_watermarked_images/{i}.jpg")
orig_image_w.save(f"watermarked_images/{i}.jpg")
```

**Comment by jinganglang567** [comment]
doctor i am setting the wandb offline model and then upload

**Comment by YuxinWenRick** [comment]
I see. Did you try the solution I posted above by saving them not through wandb?

**Comment by jinganglang567** [comment]
thanks doctor i can see the  image, but i have another question :         
TPR@1%FPR 1.0
wandb:               acc 1.0
wandb:               auc 1.0
wandb:   clip_score_mean 0.36833
wandb:    clip_score_std 0.03077
wandb: w_clip_score_mean 0.37428
wandb:  w_clip_score_std 0.04165
This is the  output of the terminal
Can i train my own model?

**Comment by jinganglang567** [comment]
> Hi, if I understood it correctly, do you mean you want to visualize the watermark?
> 
> For example, if you want to visualize `init_latents_w_fft`, you can use this code snippet after [line 88](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L88):
> 
> ```
>         import matplotlib.pyplot as plt
>         def visualize_tensor(tensor, name='./tmp.png'):
>             channels = tensor.squeeze(0).cpu().numpy()
>             fig, axs = plt.subplots(1, 4, figsize=(12, 3))
> 
>             for i, ax in enumerate(axs):
>                 ax.imshow(channels[i], cmap='gray')
>                 ax.set_title(f'Channel {i+1}')
>                 ax.axis('off')
> 
>             plt.savefig(name)
>             plt.show()
> 
>         init_latents_w_fft = torch.fft.fftshift(torch.fft.fft2(init_latents_w), dim=(-1, -2)).real
>         visualize_tensor(init_latents_w_fft, name='./real.png')
>         init_latents_w_fft = torch.fft.fftshift(torch.fft.fft2(init_latents_w), dim=(-1, -2)).imag
>         visualize_tensor(init_latents_w_fft, name='./imag.png')
> ```
> 
> Let me know if you have any problem with running it!

sorry to bother you ,doctor. i want to know One is the initial watermark, and the other is the watermark extracted from the marked image. If I want to see the extracted watermark, what should I do

**Comment by YuxinWenRick** [comment]
Hi @jinganglang567 , you can add the same script after line [125](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L125), but you want to visualize `reversed_latents_w` instead of `init_latents_w`.

```
        import matplotlib.pyplot as plt
        def visualize_tensor(tensor, name='./tmp.png'):
            channels = tensor.squeeze(0).cpu().numpy()
            fig, axs = plt.subplots(1, 4, figsize=(12, 3))

            for i, ax in enumerate(axs):
                ax.imshow(channels[i], cmap='gray')
                ax.set_title(f'Channel {i+1}')
                ax.axis('off')

            plt.savefig(name)
            plt.show()

        init_latents_w_fft = torch.fft.fftshift(torch.fft.fft2(reversed_latents_w), dim=(-1, -2)).real
        visualize_tensor(init_latents_w_fft, name='./real.png')
        init_latents_w_fft = torch.fft.fftshift(torch.fft.fft2(reversed_latents_w), dim=(-1, -2)).imag
        visualize_tensor(init_latents_w_fft, name='./imag.png')
```

**Comment by jinganglang567** [comment]
@YuxinWenRick thank you doctor. it worked

**Comment by qym77** [comment]
> 你好@jinganglang567，我不确定 wandb 这里产生了什么问题，但您可能希望在本地保存它们。
> 
> 您可以尝试将以下代码片段添加到[这里](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L150)吗？
> 
> ```
> import os
> from PIL import Image
> 
> if not os.path.exists("non_watermarked_images"):
>     os.makedirs("non_watermarked_images")
> 
> if not os.path.exists("watermarked_images"):
>     os.makedirs("watermarked_images")
> 
> orig_image_no_w.save(f"non_watermarked_images/{i}.jpg")
> orig_image_w.save(f"watermarked_images/{i}.jpg")
> ```

sorry to bother u,new to code,not familiar with wandb, if i want to save  and see the generated watermarked images,where and how should i change the code, try the method u mention above,but here is an error

**Comment by qym77** [comment]
> > 你好@jinganglang567，我不确定 wandb 这里产生了什么问题，但您可能希望在本地保存它们。
> > 您可以尝试将以下代码片段添加到[这里](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L150)吗？
> > ```
> > import os
> > from PIL import Image
> > 
> > if not os.path.exists("non_watermarked_images"):
> >     os.makedirs("non_watermarked_images")
> > 
> > if not os.path.exists("watermarked_images"):
> >     os.makedirs("watermarked_images")
> > 
> > orig_image_no_w.save(f"non_watermarked_images/{i}.jpg")
> > orig_image_w.save(f"watermarked_images/{i}.jpg")
> > ```
> 
> sorry to bother u,new to code,not familiar with wandb, if i want to save and see the generated watermarked images,where and how should i change the code, try the method u mention above,but here is an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tree_ring_watermark.py", line 232, in <module>
    main(args)
  File "run_tree_ring_watermark.py", line 27, in main
    scheduler = DPMSolverMultistepScheduler.from_pretrained(args.model_id, subfolder='scheduler')
  File "/mnt/traffic/home/qinyiming/.conda/envs/watermark/lib/python3.8/site-packages/diffusers/schedulers/scheduling_utils.py", line 118, in from_pretrained
    config, kwargs = cls.load_config(
  File "/mnt/traffic/home/qinyiming/.conda/envs/watermark/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 354, in load_config
    raise EnvironmentError(
OSError: stabilityai/stable-diffusion-2-1-base does not appear to have a file named scheduler_config.json.
wandb: 🚀 View run no_attack at: https://wandb.ai/qin1ming77-henan-university/diffusion_watermark/runs/yxz4g74p
wandb: ⭐️ View project at: https://wandb.ai/qin1ming77-henan-university/diffusion_watermark
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240802_153649-yxz4g74p/logs
wandb: WARNING The new W&B backend becomes opt-out in version 0.18.0; try it out with `wandb.require("core")`! See https://wandb.me/wandb-core for more information.

here is the error, but i search and think it seems the version doesn't match or something,how can i don't use wandb at all?or has anyother way to get the result?

**Comment by jinganglang567** [comment]
@qym77 i think the pre-trained model is not download

**Comment by qym77** [comment]
can i please ask where to download and how should i put it or do something to use the pretrained model?
