### ISSUE TITLE
The evaluation criterion for determining whether a watermark is added.

### ISSUE THREAD

**Issue by LIEEEEEEEEEE** [YuxinWenRick/tree-ring-watermark#20]
In the experiments of attacking image rotation and image cropping, which criterion is used to evaluate whether a watermark is added in the experiments, the criteria of run_tree_ring_watermark.py or the criteria of p_values?

**Comment by YuxinWenRick** [comment]
Hi, by default in this [repo](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/scripts/tree_ring.sh), we are using the l1 distance as the statistics, and we plot the roc curve.

However, if you want to use p_values, you can simply replace [eval_watermark](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L127) function with [get_p_value](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/optim_utils.py#L231).

**Comment by xinxinzi8** [comment]
Hello, could you please tell me why "negative" no_w_metric is used here: no_w_metrics.append(-no_w_metric). Thank you very much~

**Comment by YuxinWenRick** [comment]
Hi @xinxinzi8, when calculating the ROC curve, the predictions passed [here](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L158C56-L158C61) should represent the confidence score of an image being watermarked, with higher scores indicating a higher likelihood of the image being watermarked. Our metric, `no_w_metric` and `w_metric`, represents the distance, which is smaller for watermarked images. Therefore, we need to negate this metric before we calculate the ROC curve.
