### ISSUE TITLE
How to run it

### ISSUE THREAD

**Issue by LoveZra** [YuxinWenRick/tree-ring-watermark#22]
As a novice, I encountered an issue with images while running PyCharm. Can you tell me how to run this project? How to implement the functions of adding and detecting watermarks?
<img width="875" alt="image" src="https://github.com/YuxinWenRick/tree-ring-watermark/assets/147409274/b8a202f2-6664-432a-9863-f9f0f472fcb0">

**Comment by YuxinWenRick** [comment]
Hi @LoveZra , what version of `diffusers` are you using? It should work with diffusers == 0.11.1. The newer versions might not work.

**Comment by LoveZra** [comment]
Thank you very much for your answer. After modification, the problem shown in the following picture has appeared. Is it a problem with the CUDA version?
![3CAF0BEF1B457397B4C9BAAEB3189287](https://github.com/YuxinWenRick/tree-ring-watermark/assets/147409274/c3875010-dbef-4ca5-9850-7006021cdc05)

**Comment by LoveZra** [comment]
Thank you very much for your reply. There was a problem with CUDA out of memory when running Python run_tree_ring_watermark. py -- runname no-attack -- w_channel 3-- w_pattern ring -- start 0-- end 1-- with tracking -- w_seed=100. Why did this problem occur? Can you briefly introduce the function of run_tree_ring_watermark.py? Besides, I can't find the location of latent_watermark_fourier_fid.py, please help me!

**Comment by YuxinWenRick** [comment]
Hi, sorry for the late response.

The code should work on GPUs that have at least 4 GB of memory. Could you please let me know the amount of GPU memory you have available?

For `run_tree_ring_watermark.py,` we first inject watermark through these [lines](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L83-L87). Then, we perform attacks [here](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L102). In the end, we perform evaluate (calculate the metric) [here](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L127). All the helper functions can be located in [optim_utils.py](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/optim_utils.py).

What do you mean by `latent_watermark_fourier_fid.py`? You mean how we inject the watermark in the fourier space? It should be this [function](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/optim_utils.py#L196).

**Comment by LoveZra** [comment]
It's okay, thank you very much for your answer. Wishing you a happy new year. What do you think of this model if you want to achieve screen anti stealing. The latent_watermark_fourier_fid.py I mentioned is a command for calculating FID, but its location was not found.
<img width="517" alt="image" src="https://github.com/YuxinWenRick/tree-ring-watermark/assets/147409274/2e67e1a3-1072-4cbc-8273-95a08fe37bcd">

**Comment by YuxinWenRick** [comment]
Hi, could you clarify what you mean by "screen anti-theft measures?"

Oh, sorry about it, I think it should be `run_tree_ring_watermark_fid.py`.

**Comment by LoveZra** [comment]
The meaning of screen anti theft measures is that when we use this technology, we can prevent others from secretly taking photos of our privacy information on our phones and computers, and any leaks can be tracked through watermarks.

**Comment by LoveZra** [comment]
The meaning of screen anti theft measures is that when we use this technology, we can prevent others from secretly taking photos of our privacy information on our phones and computers. In the event of a leak, we can track it through the watermark of the stolen photos.

**Comment by YuxinWenRick** [comment]
I see. That's an interesting attack. We haven't tested that before, but I think tree-ring is somehow robust to it, as long as the semantic meaning of the image is not changed.
