### ISSUE TITLE
the model location

### ISSUE THREAD

**Issue by jinganglang567** [YuxinWenRick/tree-ring-watermark#24]
sorry to bother you again,doctor . i run the script,However, when the program finishes running and I don't see the saved model file, am I missing something?

**Comment by YuxinWenRick** [comment]
Hi, do you mean the stable diffusion model weights? It should be saved in the default huggingface cache directory. You can check it through `echo $HF_HOME` with the command line or `import os; print(os.environ['HF_HOME'])` in python. The model weights should be under the directory with a name `hub` or something.

**Comment by jinganglang567** [comment]
@YuxinWenRick , sorry to bother you ,doctor.It should be that I didn't express it clearly, I mean, shouldn't 256diffusion.pt be the trained model, why when I run the command, no similar model is saved to the local area.

**Comment by jinganglang567** [comment]
@YuxinWenRick doctor, sorry to bother you again, I want to convert the Fourier transform to the wavelet transform and deal with the noise, what should I do?

**Comment by YuxinWenRick** [comment]
Oh, you meant the ImageNet model? You may download the model manually through this [link](https://openaipublic.blob.core.windows.net/diffusion/jul-2021/256x256_diffusion.pt).

I don't know what's the best way to do wavelet transform in python, but I found this [library](https://pywavelets.readthedocs.io/en/latest/ref/dwt-discrete-wavelet-transform.html). Hope it's useful for you.

**Comment by jinganglang567** [comment]
@YuxinWenRick thank you doctor, i got it.
