### ISSUE TITLE
code error: AttributeError: 'bool' object has no attribute '__module__'

### ISSUE THREAD

**Issue by asdcaszc** [YuxinWenRick/tree-ring-watermark#25]
Good job. Thanks for your sharing. I have a code problem in my own computer. 

super(InversableStableDiffusionPipeline, self).__init__(vae,

super(ModifiedStableDiffusionPipeline, self).__init__(vae,

AttributeError: 'bool' object has no attribute '__module__'

However, I don't find any code using this one. Do you know how to solve this problem?

**Comment by YuxinWenRick** [comment]
Hi, could you check what `diffusers` version you are using? This code might not be compatible with the higher `diffusers` version than 0.11.1. You can also check out this [implementation](https://huggingface.co/spaces/devingulliver/dendrokronos). I think they reimplemented the method with the latest `diffusers` version.

**Comment by asdcaszc** [comment]
Yes, the problem is the different version. Thanks for your advice.
