### ISSUE TITLE
Watermarking pre generated images

### ISSUE THREAD

**Issue by Ashh-Z** [YuxinWenRick/tree-ring-watermark#31]
Hi, thanks for your work. 
I am not able to understand, what changes should I make to watermark my pre generated images ? The code files seem to only run and test on some pre-defined datasets or create watermarked images using text prompts. 
Any advice would be greatly appreciated. 
Thanks

**Comment by Ashh-Z** [comment]
Ah, I guess the process won't support this. I understand now. Thank you

**Comment by YuxinWenRick** [comment]
Hi, yeah, you are right that tree-ring doesn't support watermarking existing images, but you can checkout this paper: https://arxiv.org/abs/2401.04247. They are able to watermark existing images with the tricks similar to tree-ring.
