### ISSUE TITLE
InversableStableDiffusionPipeline class incompatible SDXL, can do some upgrade?

### ISSUE THREAD

**Issue by Ashlars** [YuxinWenRick/tree-ring-watermark#32]

**Comment by YuxinWenRick** [comment]
Hi, you can checkout this huggingface space: https://huggingface.co/spaces/devingulliver/dendrokronos/blob/main/app.py. They are running with SDXL. For the latest diffusers, you can use [DDIMInverseScheduler](https://huggingface.co/spaces/devingulliver/dendrokronos/blob/main/app.py#L84) for the inversion.

**Comment by Ashlars** [comment]
Thank you, I will give it a go :)
