### ISSUE TITLE
about the pipeline

### ISSUE THREAD

**Issue by jinganglang567** [YuxinWenRick/tree-ring-watermark#34]
sorry to bother you again,doctor,Pipeline training is always going to explode the memory, so I'm thinking about whether I can use the distributed training of the pipeline or avoid the use of the pipeline

**Comment by YuxinWenRick** [comment]
Hi, I’m not sure which training you’re referring to. It could be a wrong repo?

**Comment by jinganglang567** [comment]
Sorry, doctor, I don't think my description is clear, the code is implemented in the Pipeline mechanism of Diffusers,such as InversableStableDiffusionPipeline or ModifiedStableDiffusionPipeline.But when I run the program on a 3090 graphics card, it works fine. And it didn't work in the 1080ti, because it is out of memory. Now i want to ask if i want to run in four 1080ti.For example, run custom pipieline in a distributed manner.what shoud i do?
the error is alway like that
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 10.91 GiB total capacity; 9.85 GiB already allocated; 94.19 MiB free; 9.97 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by YuxinWenRick** [comment]
Hi, this doesn't look right to me. The code only uses ~6 GiB memory on my GPU, so your 1080Ti should work too. Did you make any modifications to the code? Can you double-check if you are using float16 and also generating one image at a time?

**Comment by jinganglang567** [comment]
yes ,i made a little change to the inverse_stable_diffusion.py ,i added a function called edcorrector


      def edcorrector(self, x, encoder_hidden_states):
        input = x.clone().float()
        z = self.get_image_latents(x).clone().float() # initial z
      
        z.requires_grad_(True)
       
       
        loss_function = torch.nn.MSELoss(reduction='sum')
        losses = []
       optimizer = torch.optim.Adam([z], lr=1e-2)
        
        
        t =self.scheduler.timesteps[-1]
        scheduler = copy.deepcopy(self.scheduler)
        
        unet = copy.deepcopy(self.unet).float()

  
        lam = 1

    
        z_output = copy.deepcopy(z)
        z_output = scheduler.convert_model_output(z_output, t, z)
        z_output = scheduler.step(z_output, t, z).prev_sample
          for i in range(1000):
            x_pred = self.decode_image_for_gradient_float(z)
            loss = loss_function(x_pred, input) + torch.norm(z)
            loss1 = loss_function(x_pred, input).detach()
            loss2 = torch.norm(z)
            if i%200==0:
                print(f"t: {0}, Iteration {i}, Loss1: {loss1.item()}, Loss2: {loss2.item()}")
            
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
return z.half()

`

then i run the script [run_tree_ring_watermark](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py)
here add `image_latents_w_modified = pipe.edcorrector(pipe.decode_image(test),text_embeddings) # input as the image
        image_latents_w_modified_clone=image_latents_w_modified.clone()`
