### ISSUE TITLE
Is this all the requirements needs?

### ISSUE THREAD

**Issue by qym77** [YuxinWenRick/tree-ring-watermark#37]
sorry new to code,but after install the package in requirements.txt when i run python run_tree_ring_watermark.py --run_name no_attack --w_channel 3 --w_pattern ring --start 0 --end 1000 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k,, it seems always missing packages

**Comment by qym77** [comment]
Actually, i have few more questions, i don't know which version wandb is needed, i simply run "pip install wandb"
,but seems doesn't work

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tree_ring_watermark.py", line 217, in <module>
    main(args)
  File "run_tree_ring_watermark.py", line 27, in main
    scheduler = DPMSolverMultistepScheduler.from_pretrained(args.model_id, subfolder='scheduler')
  File "/mnt/traffic/home/qinyiming/.conda/envs/watermark/lib/python3.8/site-packages/diffusers/schedulers/scheduling_utils.py", line 118, in from_pretrained
    config, kwargs = cls.load_config(
  File "/mnt/traffic/home/qinyiming/.conda/envs/watermark/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 354, in load_config
    raise EnvironmentError(
OSError: stabilityai/stable-diffusion-2-1-base does not appear to have a file named scheduler_config.json.
wandb: 🚀 View run no_attack at: https://wandb.ai/qin1ming77-henan-university/diffusion_watermark/runs/1o9y15xt
wandb: ⭐️ View project at: https://wandb.ai/qin1ming77-henan-university/diffusion_watermark
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240802_151629-1o9y15xt/logs
wandb: WARNING The new W&B backend becomes opt-out in version 0.18.0; try it out with `wandb.require("core")`! See https://wandb.me/wandb-core for more information.

**Comment by qym77** [comment]
can i ask few more questions, if i want to save the images generated in this way and watermarked removed images, do i need to add some code or juest run "python run_tree_ring_watermark.py --run_name no_attack --w_channel 3 --w_pattern ring --start 0 --end 1000 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k" to see the result?

**Comment by YuxinWenRick** [comment]
Hi @qym77, sorry for the late reply. I was a little busy with the NeurIPS rebuttal.

I think your problem might be with the package version. Can you check if you are using:
```
PyTorch == 1.13.0
transformers == 4.23.1
diffusers == 0.11.1
```
The current code only supports very old diffusers version, but you check this reimplementation for the latest diffusers: https://huggingface.co/spaces/devingulliver/dendrokronos/blob/main/app.py. It's very clean.

For saving the images, you can do something like this: https://github.com/YuxinWenRick/tree-ring-watermark/issues/19#issuecomment-1969269423. But you put them at [line 103](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L103), and save `orig_image_w` (watermarked image) and `orig_image_w_auged` (after attack) separately.

Let me know if you have further questions!

**Comment by qym77** [comment]
> Hi @qym77, sorry for the late reply. I was a little busy with the NeurIPS rebuttal.
> 
> I think your problem might be with the package version. Can you check if you are using:
> 
> ```
> PyTorch == 1.13.0
> transformers == 4.23.1
> diffusers == 0.11.1
> ```
> 
> The current code only supports very old diffusers version, but you check this reimplementation for the latest diffusers: https://huggingface.co/spaces/devingulliver/dendrokronos/blob/main/app.py. It's very clean.
> 
> For saving the images, you can do something like this: [#19 (comment)](https://github.com/YuxinWenRick/tree-ring-watermark/issues/19#issuecomment-1969269423). But you put them at [line 103](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L103), and save `orig_image_w` (watermarked image) and `orig_image_w_auged` (after attack) separately.
> 
> Let me know if you have further questions!

sorry to bother u,here are problems still not solved, my PyTorch is 1.10.0，the others is the same version,and does the issue"No module named 'datasets' " really can be solved by "pip install datasets"? because after i run this,it seems install many packages but not you mentioned in the other reply

**Comment by qym77** [comment]
whats more i get other error is"AttributeError: module 'wandb' has no attribute 'init' ", i think because the wandb version,but actually i dont need to track now,at least. I just want to save the images generated in this way and images after attack,so i set the args.--with_tracking False,but it still have this error

**Comment by YuxinWenRick** [comment]
Hi @qym77 , sorry about all the confusion, `--with_tracking` is a "store_true" argument, if you don't want to use wandb, you can simply delete `--with_tracking` in your command line.

Let me know if you still have trouble running the code!
