### ISSUE TITLE
Visualizing the watermark patterns

### ISSUE THREAD

**Issue by Ashh-Z** [YuxinWenRick/tree-ring-watermark#38]
Zeros : 
![image](https://github.com/user-attachments/assets/04f237ff-bc91-4a26-941d-eda05f7a012c)

Rand : 
![image](https://github.com/user-attachments/assets/5fae0c85-e341-4f1b-9d05-e53977894e0f)

Ring : 
![image](https://github.com/user-attachments/assets/c0982841-83c8-4406-8b29-cfcc1fefb055)

I tried visualizing all the three watermarking patterns. Could you please verify if these are the expected results?

**Comment by YuxinWenRick** [comment]
Yes, I believe they look like as they should.
