### ISSUE TITLE
About p-value

### ISSUE THREAD

**Issue by lifeofstudy** [YuxinWenRick/tree-ring-watermark#40]
Hello, thank you for your excellent work. I have a question about p-value. In your paper, you introduced that p-value can be used for watermark detection, but in the code implementation, you used the threshold corresponding to %1FPR as the detection threshold. Is my understanding correct?

**Comment by YuxinWenRick** [comment]
Hi, yes, we didn't use p-value for our experiments, since we wrote the p-value formula down after we ran all the experiments. Sorry about the confusion.

Let me know if you have any further questions!
