### ISSUE TITLE
Hi I want replicate your work but I think the datasets.py file is missing or do I need to create one myself?

### ISSUE THREAD

**Issue by Xdarii** [YuxinWenRick/tree-ring-watermark#5]
https://github.com/YuxinWenRick/tree-ring-watermark/blob/8ff17113d4138491dc330566bb1f1ad457c76ea0/optim_utils.py#L3

**Comment by YuxinWenRick** [comment]
Hi, sorry about confusion. It's actually just huggingface datasets library. You can just simply install it with `pip install datasets`, https://huggingface.co/docs/datasets/installation.
