### ISSUE TITLE
Regarding the code for unconditional diffusion model on Imagenet

### ISSUE THREAD

**Issue by njuaplusplus** [YuxinWenRick/tree-ring-watermark#7]
Thanks for this interesting work.

I didn't see the code for the DDIM experiments. Could you upload the code to this repo? Thank you very much.

**Comment by YuxinWenRick** [comment]
Hi, thanks for your interest.

Sorry about the confusion. The current code uses `DPMSolverMultistepScheduler`, but in my past experience, `DPMSolverMultistepScheduler` performs very similarly to DDIM, so I kept this from the huggingface example code. However, if you want to use DDIM, you can just replace this [line]( https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L27), with `scheduler = DDIMScheduler.from_config(pipe.scheduler.config)`, and import `DDIMScheduler` from diffusers.

**Comment by njuaplusplus** [comment]
Thanks for your reply. Sorry that I didn't state it clearly. I was referring to the code for the experiments on the unconditional diffusion model on Imagenet.

**Comment by YuxinWenRick** [comment]
Oh, I see.

I'm kind of busy with the conference deadline recently, but I will try my best to clean the code and update it by the end of this month. Thanks for your patience.

**Comment by linju2022perfect** [comment]
> Thanks for your reply. Sorry that I didn't state it clearly. I was referring to the code for the experiments on the unconditional diffusion model on Imagenet.

Hello, you ran into a ModuleNotFoundError: No module named 'datasets' this one?

**Comment by YuxinWenRick** [comment]
Hi @linju2022perfect, sorry about the confusion. It's actually just huggingface datasets library. You can simply install it with `pip install datasets`, https://huggingface.co/docs/datasets/installation.

**Comment by YuxinWenRick** [comment]
Hi @njuaplusplus, sorry for the delay, but I just updated the code for the ImageNet models. You can find the script [here](https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/scripts/tree_ring_imagenet.sh). Meanwhile, you may want to download the pre-trained model with this link: https://openaipublic.blob.core.windows.net/diffusion/jul-2021/256x256_diffusion.pt.

Let me know if you have any further questions!
